name: Enforce PR labels

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: yogevbd/enforce-label-action@2.1.0
      with:
        REQUIRED_LABELS_ANY: "ready to release"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Assign `ready to release` label to CI/CD"
        BANNED_LABELS: "banned"
