name: Test CI

on:
  pull_request:
    branches: [master, staging]

jobs:
  quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
  
      - run: npm ci
      - run: npm run build:all --if-present
      - run: npx semantic-release --dry-run --no-ci --branches ${{ github.head_ref }}
